url: https://github.com/mozilla/openbadges-directory
safe: true
lsi: false
source: .
destination: ./public
exclude:
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
  - ./public
markdown: rdiscount
pygments: false
port: 9876
baseurl: /openbadges-directory
